/*
Dawson Fedor Janura
Game of Life frame
 */
package cams;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author darek1849
 */
public class CAMS_GameOfLife extends javax.swing.JFrame {

    // reference main cuz this is second window
    CAMS_Mainframe main;
    private JPanel plane;

    public Cell[][] map;

    public CAMS_GameOfLife(CAMS_Mainframe m) {
        initComponents();
        // add it

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        map = new Cell[100][100];

        //need to add toolbar to game of life as well, will implement later today
	    
        //the actual functionality of the plane does not work properly
        plane = new GameOfLifePlane(map.length, map[0].length, map, this);

        plane.setVisible(true);
        add(plane, BorderLayout.CENTER);
        pack();

        setSize(1000, 800);
        setTitle("Application");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// send back to first window

    private void golHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_golHomeBtnActionPerformed
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_golHomeBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton golHomeBtn;
    // End of variables declaration//GEN-END:variables
}

