/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cams;

import javax.swing.JPanel;

/**
 *
 * @author darek1849
 */
public class CAMS_WireWorld extends javax.swing.JFrame {

    CAMS_Mainframe main;
    
    private JPanel plane;
    
    public Cell[][] map;
    
    public CAMS_WireWorld(CAMS_Mainframe m) {
        initComponents();
        main = m;
        
       
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	map = new Cell[100][100];
    	plane = new WireworldPlane(map.length, map[0].length, map, this);
        
        plane.setVisible(true);
        add(plane,BorderLayout.CENTER);
		pack();
		
		setSize(1000,800);
		setTitle("Application");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void wwHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wwHomeBtnActionPerformed

        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_wwHomeBtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton wwHomeBtn;
    // End of variables declaration//GEN-END:variables
}
