/*
 * Dawson, Janura, Fedor
 * May 28, 2024
 * Mainframe class
 */
package cams;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author darek1849
 */
public class CAMS_Mainframe extends javax.swing.JFrame {

    // second window of user manual
    private CAMS_UserManual userManual;
    // second window of wireworld
    private CAMS_WireWorld wireWorld;
    // second window of game of life
    private CAMS_GameOfLife gameOfLife;

    public CAMS_Mainframe() {
        initComponents();
        Cursor cursor;
        cursor = Toolkit.getDefaultToolkit().createCustomCursor(new ImageIcon(getClass().getResource("/cams/images/pointer_scifi_b.png")).getImage(), new Point(), "Custom cursor");
        setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        GOLbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        WWbtn = new javax.swing.JButton();
        userManbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 218, 105));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));

        titleLbl.setFont(new java.awt.Font("PT Mono", 1, 36)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("CAMS");

        GOLbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/gameoflife1.png"))); // NOI18N
        GOLbtn.setToolTipText("");
        GOLbtn.setBorder(null);
        GOLbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        GOLbtn.setFocusPainted(false);
        GOLbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GOLbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GOLbtnMouseReleased(evt);
            }
        });
        GOLbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOLbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Cellular Automata Model Simulations");

        WWbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/wireworld1.png"))); // NOI18N
        WWbtn.setBorder(null);
        WWbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WWbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                WWbtnMouseReleased(evt);
            }
        });
        WWbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WWbtnActionPerformed(evt);
            }
        });

        userManbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/usermanual1.png"))); // NOI18N
        userManbtn.setBorder(null);
        userManbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userManbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userManbtnMouseReleased(evt);
            }
        });
        userManbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManbtnActionPerformed(evt);
            }
        });

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/exit1.png"))); // NOI18N
        exitbtn.setBorder(null);
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitbtnMouseReleased(evt);
            }
        });
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("by: Janura, Fedor, and Dawson");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(userManbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WWbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GOLbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(GOLbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WWbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userManbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       

    private void exitbtnMouseReleased(java.awt.event.MouseEvent evt) {                                      
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/exit1.png"))); // NOI18N
    }                                     

    private void exitbtnMousePressed(java.awt.event.MouseEvent evt) {                                     
        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/exit2.png"))); // NOI18N
    }                                    

    private void userManbtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // check if second window has been created
        if (userManual == null) {
            userManual = new CAMS_UserManual(this);
        }
        // set the other window to be visible
        userManual.setVisible(true);
        // hide og window
        this.setVisible(false);
    }                                          

    private void userManbtnMouseReleased(java.awt.event.MouseEvent evt) {                                         
        userManbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/usermanual1.png"))); // NOI18N
    }                                        

    private void userManbtnMousePressed(java.awt.event.MouseEvent evt) {                                        
        userManbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/usermanual2.png"))); // NOI18N
    }                                       

    private void WWbtnActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // check if second window has been created
        if (wireWorld == null) {
            try {
                wireWorld = new CAMS_WireWorld(this);
            } catch (IOException ex) {
                Logger.getLogger(CAMS_Mainframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // set the other window to be visible
        wireWorld.setVisible(true);
        // hide og window
        this.setVisible(false);
    }                                     

    private void WWbtnMouseReleased(java.awt.event.MouseEvent evt) {                                    
        WWbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/wireworld1.png"))); // NOI18N
    }                                   

    private void WWbtnMousePressed(java.awt.event.MouseEvent evt) {                                   
        WWbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/wireworld2.png"))); // NOI18N
    }                                  

    private void GOLbtnActionPerformed(java.awt.event.ActionEvent evt) {                                       

        // check if second window has been created

        if (gameOfLife == null) {

            try {
                gameOfLife = new CAMS_GameOfLife(this);
            } catch (IOException ex) {
                Logger.getLogger(CAMS_Mainframe.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        // set the other window to be visible
        gameOfLife.setVisible(true);
        // hide og window
        this.setVisible(false);
    }                                      

    private void GOLbtnMouseReleased(java.awt.event.MouseEvent evt) {                                     
        GOLbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/gameoflife1.png"))); // NOI18N
    }                                    

    private void GOLbtnMousePressed(java.awt.event.MouseEvent evt) {                                    
        GOLbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cams/images/gameoflife2.png"))); // NOI18N
    }                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAMS_Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAMS_Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAMS_Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAMS_Mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CAMS_Mainframe().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton GOLbtn;
    private javax.swing.JButton WWbtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton userManbtn;
    // End of variables declaration                   
}

